#!/usr/bin/env python2
# vim:fileencoding=utf-8
from __future__ import unicode_literals, division, absolute_import, print_function
from calibre.web.feeds.news import BasicNewsRecipe

class AdvancedUserRecipe1525856516(BasicNewsRecipe):
    title          = 'Rosa Template'
    oldest_article = 7
    max_articles_per_feed = 100
    auto_cleanup   = True

    feeds          = [
        ('Learn Piano With Rosa', 'http://learnpianowithrosa.com/'),
    ]
